//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSTrackingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class driver
    {
        public int sno { get; set; }
        public string driverid { get; set; }
        public string drivername { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string cpassword { get; set; }
        public string vehicleno { get; set; }
        public string driverimg { get; set; }
    }
}
