//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSTrackingWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mygpsEntities2 : DbContext
    {
        public mygpsEntities2()
            : base("name=mygpsEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<persontracking> persontrackings { get; set; }
        public DbSet<feedback> feedbacks { get; set; }
        public DbSet<login> logins { get; set; }
        public DbSet<ownertracking> ownertrackings { get; set; }
        public DbSet<vehicletracking> vehicletrackings { get; set; }
        public DbSet<driver> drivers { get; set; }
        public DbSet<personallonglat> personallonglats { get; set; }
    }
}
