//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSTrackingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class persontracking
    {
        public int sno { get; set; }
        public string pid { get; set; }
        public string pname { get; set; }
        public string email { get; set; }
        public string contact { get; set; }
        public string rcontact1 { get; set; }
        public string rcontact2 { get; set; }
        public string rcontact3 { get; set; }
        public string rcontact4 { get; set; }
        public string pimg { get; set; }
        public string password { get; set; }
        public string repassword { get; set; }
    }
}
