//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSTrackingWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicletracking
    {
        public int sno { get; set; }
        public string driverid { get; set; }
        public string vno { get; set; }
        public string permitno { get; set; }
        public string permittype { get; set; }
        public string company { get; set; }
        public string avgspeed { get; set; }
        public string fueltank { get; set; }
        public string currenttankstatus { get; set; }
    }
}
